# Runs 2 Jobs in Parallel until 10 Jobs gets completed
apiVersion: batch/v1
kind: Job
metadata:
  name: counting-job
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      name: counting-job
    spec:
      containers:
        - name: count
          image: centos:7
          command:
            - /bin/sh
            - -c
            - "for i in $(seq 1 10); do echo count: $i; sleep 1; done"
      restartPolicy: Never
