apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pv1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    selector:
      matchLabels:
        type: local
