#secrer via Enivirinment Variable

apiVersion: v1
kind: Pod
metadata:
  name: mysecret-env-pod

spec:
  containers:
    - name: mysecret-env-container
      image: redis
      env:
        - name: MY_SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username

        - name: MY_SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never
