apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nec
  name: pod-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "update", "list","watch", "create", "delete"]

  